server:
  port: 5010
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_stu_sys?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    hikari:
      max-lifetime: 500000
      maximum-pool-size: 100
mybatis-plus:
  mapper-locations: classpath:static/mybatis/mapper/*.xml