server:
  port: 5001
spring:
  datasource:
    username: root
    password: qycssg!0
      #    password: 123456
    url: jdbc:mysql://101.200.201.196:3306/db_stu_sys?serverTimezone=GMT%2B8&useSSL=false
      #    url: jdbc:mysql://localhost:3306/db_stu_sys?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    proxy-target-class: true

#mybatis:
#  config-location: classpath:static/mybatis/mybatis.xml
#  mapper-locations: classpath:static/mybatis/mapper/*.xml
mybatis-plus:
  mapper-locations: classpath:static/mybatis/mapper/*.xml

