package com.bean;

import com.baomidou.mybatisplus.annotation.DbType;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.generator.AutoGenerator;
import com.baomidou.mybatisplus.generator.config.DataSourceConfig;
import com.baomidou.mybatisplus.generator.config.GlobalConfig;
import com.baomidou.mybatisplus.generator.config.PackageConfig;
import com.baomidou.mybatisplus.generator.config.StrategyConfig;
import com.baomidou.mybatisplus.generator.config.rules.DateType;
import com.baomidou.mybatisplus.generator.config.rules.NamingStrategy;

/**
 * @author qyc
 * @time 2020/8/11 - 10:42
 */
public class AutoGeneratedCode {
    static void contextLoads() {
        //创建代码生成器
        AutoGenerator autoGenerator = new AutoGenerator();

        //全局配置
        GlobalConfig globalConfig = new GlobalConfig();
//        String path = System.getProperty("user.dir");
//        System.out.println(path);
        String path = "G:\\IDEA source\\student_information_management_system\\util_module";
        globalConfig.setOutputDir(path+"/src/main/java");
        globalConfig.setAuthor("testjava");
        globalConfig.setOpen(false);
        globalConfig.setFileOverride(true);  //不覆盖
        globalConfig.setServiceName("%sService"); //去掉接口首字母I
        globalConfig.setIdType(IdType.AUTO);  //主键生成策略
        globalConfig.setDateType(DateType.ONLY_DATE);
//        globalConfig.setSwagger2(true); //开启swagger2模式
        autoGenerator.setGlobalConfig(globalConfig);

        //数据源配置
        DataSourceConfig dataSourceConfig = new DataSourceConfig();
        dataSourceConfig.setUrl("jdbc:mysql://101.200.201.196:3306/db_stu_sys?serverTimezone=GMT%2B8&useSSL=false");
        dataSourceConfig.setDriverName("com.mysql.jdbc.Driver");
        dataSourceConfig.setUsername("root");
        dataSourceConfig.setPassword("qycssg!0");
        dataSourceConfig.setDbType(DbType.MYSQL);
        autoGenerator.setDataSource(dataSourceConfig);

        //包配置
        PackageConfig packageConfig = new PackageConfig();
        packageConfig.setParent("com");
//        packageConfig.setModuleName("plus");
//        packageConfig.setController("controller");
        packageConfig.setEntity("bean");
//        packageConfig.setService("service");
//        packageConfig.setMapper("mapper");
        autoGenerator.setPackageInfo(packageConfig);

        //策略配置
        StrategyConfig strategyConfig = new StrategyConfig();

        strategyConfig.setInclude("college_admin"); //表

        strategyConfig.setNaming(NamingStrategy.underline_to_camel); //库表映射策略
        strategyConfig.setTablePrefix(packageConfig.getModuleName()+"_"); //生成实体是去掉表前缀
        strategyConfig.setColumnNaming(NamingStrategy.underline_to_camel); //字段映射策略
        strategyConfig.setEntityLombokModel(true); //lombok模型
//        strategyConfig.setRestControllerStyle(true);
        strategyConfig.setControllerMappingHyphenStyle(true);
        autoGenerator.setStrategy(strategyConfig);
        autoGenerator.execute();
    }

    public static void main(String[] args) {

        contextLoads();
//        String id = RandomUtil.randomNumbers(8);
//        System.out.println(id);
    }
}
